// study-notes/subjects/vue/05-Vue3核心语法/src/05_compositionAPI基础/Home.vue
<template>
  <div>
    Home Page
    <h2>{{ message }}</h2>
    <h2>当前计数: {{ counter }}</h2>
    <button @click="increment">+1</button>
  </div>
</template>

<script>
import { ref } from 'vue';

export default {
  props: {
    message: {
      type: String,
      required: true,
    },
  },
  setup() {
    let counter = 100;
    // 局部函数
    const increment = () => {
      counter++;
      console.log(counter);
    };
    return {
      counter,
      increment,
    };
  },
};
</script>

<style scoped></style>

// study-notes/subjects/react/05-React Hooks/src/05_useReducer使用/home.js
import React, { useState, useReducer } from 'react'

import reducer from './reducer'

export default function Home() {
  // const [count, setCount] = useState(0)
  const [state, dispatch] = useReducer(reducer, { counter: 0 })

  return (
    <div>
      <h2>Home当前计数: {state.counter}</h2>
      <button onClick={e => dispatch({ type: 'increment' })}>+1</button>
      <button onClick={e => dispatch({ type: 'decrement' })}>-1</button>
    </div>
  )
}
