// study-notes/subjects/vue/03-Vue3组件化开发/src/05_商品页面的切换/TabControl.vue
<template>
  <div class="tab-control">
    <div
      class="tab-control-item"
      :class="{ active: currentIndex === index }"
      v-for="(title, index) in titles"
      :key="title"
      @click="itemClick(index)"
    >
      <span>{{ title }}</span>
    </div>
  </div>
</template>

<script>
export default {
  emits: ['titleClick'],
  props: {
    titles: {
      type: Array,
      default() {
        return [];
      },
    },
  },
  data() {
    return {
      currentIndex: 0,
    };
  },
  methods: {
    itemClick(index) {
      this.currentIndex = index;
      this.$emit('titleClick', index);
    },
  },
};
</script>

<style scoped>
.tab-control {
  display: flex;
}
.tab-control-item {
  flex: 1;
  text-align: center;
}
.tab-control-item.active {
  color: red;
}

.tab-control-item.active span {
  border-bottom: 3px solid red;
  padding: 5px 10px;
}
</style>

// study-notes/subjects/react/02-React核心语法/src/04_组件通信案例/TabControl.js
import React, { Component } from 'react'
import PropTypes from 'prop-types'

export default class TabControl extends Component {
  constructor(props) {
    super(props)

    this.state = {
      currentIndex: 0
    }
  }

  render() {
    const { titles } = this.props
    const { currentIndex } = this.state

    return (
      <div className="tab-control">
        {
          titles.map((item, index) => {
            return (
              <div
                key={item}
                className={"tab-item " + (index === currentIndex ? "active" : "")}
                onClick={e => this.itemClick(index)}>
                <span>{item}</span>
              </div>
            )
          })
        }
      </div>
    )
  }

  itemClick(index) {
    this.setState({
      currentIndex: index
    })

    const { itemClick } = this.props
    itemClick(index)
  }
}

TabControl.propTypes = {
  titles: PropTypes.array.isRequired
}
